const GET_VIDEOGAMES = "GET_VIDEOGAMES"
const GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAMES_BY_NAME"
const GET_GENRES = "GET_GENRES"
const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
const FILTER_BY_GENRE = "FILTER_BY_GENRE"
const SORT_ALPHABETIC = "SORT_ALPHABETIC"
const SORT_RATING = "SORT_RATING"
const SORT_GENRE = "SORT_GENRE"

module.exports = {
  GET_VIDEOGAMES,
  GET_VIDEOGAMES_BY_NAME,
  GET_GENRES,
  FILTER_BY_ORIGIN,
  FILTER_BY_GENRE,
  SORT_ALPHABETIC,
  SORT_RATING,
  SORT_GENRE,
}
