const GET_VIDEOGAMES = "GET_VIDEOGAMES"
const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
const SORT_ALPHABETIC = "SORT_ALPHABETIC"
const SORT_RATING = "SORT_RATING"

module.exports = {
  GET_VIDEOGAMES,
  FILTER_BY_ORIGIN,
  SORT_ALPHABETIC,
  SORT_RATING,
}
